# Generated by Django 2.1.5 on 2019-03-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0002_auto_20190309_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdata',
            name='Task',
            field=models.TextField(default='Null value', max_length=100),
        ),
    ]
