# Generated by Django 2.1.5 on 2019-03-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0003_auto_20190309_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdata',
            name='Task',
            field=models.TextField(max_length=100),
        ),
    ]
